word_swapping:
  - type: wordswap
    num_return_sequences: 4
    label: word_swapping_wordswap
  - type: wordnet
    num_return_sequences: 4
    label: word_swapping_wordnet
back_translation:
  - target_language: de
    num_return_sequences: 4
    label: back_translation_de
  - target_language: fi
    num_return_sequences: 4
    label: back_translation_fi
  - target_language: en
    num_return_sequences: 4
    label: back_translation_en
  - target_language: ru
    num_return_sequences: 4
    label: back_translation_ru    
stopwords_filtering:
  - num_return_sequences: 1 # fixed
    label: stopwords_filtering